apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authn.fullname" . }}
  labels: {{- include "authn.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  APP_DEBUG: {{ .Values.env.APP_DEBUG | quote }}
  LOG_CHANNEL: {{ .Values.env.LOG_CHANNEL | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  CACHE_STORE: {{ .Values.env.CACHE_STORE | quote }}
  QUEUE_CONNECTION: {{ .Values.env.QUEUE_CONNECTION | quote }}
  SESSION_DRIVER: {{ .Values.env.SESSION_DRIVER | quote }}
  AUTHN_APP_URL: {{ .Values.env.AUTHN_APP_URL | quote }}
  APP_URL: {{ .Values.env.AUTHN_APP_URL | quote }}
  AUTHN_ROUTING_MODE: {{ .Values.env.AUTHN_ROUTING_MODE | quote }}
  AUTHN_DEFAULT_FROM_EMAIL: {{ .Values.env.AUTHN_DEFAULT_FROM_EMAIL | quote }}
  DB_CONNECTION: pgsql
  DB_HOST: {{ include "authn.dbHost" . | quote }}
  DB_PORT: {{ include "authn.dbPort" . | quote }}
  DB_DATABASE: {{ include "authn.dbName" . | quote }}
  DB_USERNAME: {{ include "authn.dbUser" . | quote }}
  REDIS_CLIENT: phpredis
  REDIS_HOST: {{ include "authn.redisHost" . | quote }}
  REDIS_PORT: {{ include "authn.redisPort" . | quote }}
  MAIL_MAILER: {{ .Values.env.MAIL_MAILER | quote }}
  MAIL_HOST: {{ .Values.env.MAIL_HOST | quote }}
  MAIL_PORT: {{ .Values.env.MAIL_PORT | quote }}
  MAIL_FROM_ADDRESS: {{ .Values.env.MAIL_FROM_ADDRESS | quote }}
  MAIL_FROM_NAME: {{ .Values.env.MAIL_FROM_NAME | quote }}
