apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authn.fullname" . }}-worker
  labels:
    {{- include "authn.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      {{- include "authn.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "authn.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-app.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "authn.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: {{ include "authn.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - php
            - artisan
            - queue:work
            - --queue=default,webhooks,mail
            - --tries=3
            - --max-time=3600
            - --sleep=1
            - --backoff=10
          envFrom:
            - configMapRef:
                name: {{ include "authn.fullname" . }}
            - secretRef:
                name: {{ include "authn.secretName" . }}
          {{- with .Values.extraEnv }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          resources: {{- toYaml .Values.resources.worker | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
