{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authn.fullname" . }}-scheduler
  labels:
    {{- include "authn.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "authn.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        {{- include "authn.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: scheduler
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-app.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "authn.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: scheduler
          image: {{ include "authn.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          command: [php, artisan, schedule:work]
          envFrom:
            - configMapRef:
                name: {{ include "authn.fullname" . }}
            - secretRef:
                name: {{ include "authn.secretName" . }}
          resources: {{- toYaml .Values.resources.scheduler | nindent 12 }}
{{- end }}
