{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "authn.fullname" . }}-web
  labels:
    {{- include "authn.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "authn.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
