{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authn.fullname" . }}
  labels: {{- include "authn.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ required "secrets.values.APP_KEY (or secrets.existingSecret) is required" .Values.secrets.values.APP_KEY | quote }}
  AUTHN_BOOTSTRAP_ADMIN_EMAIL: {{ .Values.secrets.values.AUTHN_BOOTSTRAP_ADMIN_EMAIL | quote }}
  AUTHN_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.secrets.values.AUTHN_BOOTSTRAP_ADMIN_PASSWORD | quote }}
  AUTHN_BOOTSTRAP_WORKSPACE_NAME: {{ .Values.secrets.values.AUTHN_BOOTSTRAP_WORKSPACE_NAME | quote }}
  DB_PASSWORD: {{ .Values.secrets.values.DB_PASSWORD | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.values.REDIS_PASSWORD | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.values.MAIL_PASSWORD | quote }}
{{- end }}
